version: 2

models:

  - name: dim_date
    description: "Date dimension table"

    columns:
      - name: date_key
        description: "Primary key of date dimension"
        tests:
          - not_null
          - unique

  - name: dim_product
    description: "Product dimension table"

    columns:
      - name: product_key
        tests:
          - not_null
          - unique

  - name: dim_region
    description: "Region dimension table"

    columns:
      - name: region_key
        tests:
          - not_null
          - unique

  - name: dim_payment
    description: "Payment dimension table"

    columns:
      - name: payment_key
        tests:
          - not_null
          - unique

  - name: fact_orders
    description: "Central fact table"

    columns:

      - name: order_id
        tests:
          - not_null

      - name: date_key
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key

      - name: product_key
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_key

      - name: region_key
        tests:
          - relationships:
              to: ref('dim_region')
              field: region_key

      - name: payment_key
        tests:
          - relationships:
              to: ref('dim_payment')
              field: payment_key